import './globals.css'
import type { Metadata } from 'next'
import ThemeProvider from '@/Providers/ThemeProvider';
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import TanstackProvider from '@/Providers/TanstackProvider';
import NextTopLoader from 'nextjs-toploader'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Script from 'next/script'
import Navbar from '@/components/Navbar';
import ClerkProvider from '@/Providers/ClerkProvider';
import SideCompo from '@/components/SideCompo';
import Theme from '@/components/Theme';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ThemeProvider>
          <TanstackProvider>
            <body className={inter.className}>
              <NextTopLoader showSpinner={false} />
              <Navbar />
              <div className='relative min-h-screen'>
                <Theme />
                <SideCompo />
                {children}
                <Toaster />
              </div>
            </body>
            {/* afterInteractive is the default strategy for Next's <Script> tag */}
            <Script
                async
                strategy='afterInteractive'
                src='https://www.googletagmanager.com/gtag/js?id=G-BKK7659J87'
                />
            <Script strategy='afterInteractive' src='/analytics.js' />
          </TanstackProvider>  
        </ThemeProvider>
      </ClerkProvider>
    </html>
  )
}
