import './globals.css'
import type { Metadata } from 'next'
import ThemeProvider from '@/Providers/ThemeProvider';
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import { ThemeToggle } from '@/components/ThemeToggle'
import TanstackProvider from '@/Providers/TanstackProvider';
import NextTopLoader from 'nextjs-toploader'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <ThemeProvider>
          <TanstackProvider>
            <body className={inter.className}>
            <NextTopLoader showSpinner={false} />
              <ThemeToggle className="absolute top-2 right-6 z-50" />
              <div className='min-h-screen'>
                {children}
                <Toaster />
              </div>
            </body>
          </TanstackProvider>  
        </ThemeProvider>
      </html>
  )
}
